[package]
name = "structs"
version = "0.1.0"
authors = ["Golodnyi <ochen@golodnyi.ru>"]
[lib]
name = "structs"
path = "lib.rs"
[dependencies]
telegram-bot = { git = "https://github.com/bismuth-party/telegram-bot" }
chrono = "0.4"